# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weatr' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # my own framework
  pod 'Eatr'
  pod 'Nativefier'
  
  pod 'HandyJSON'
  pod 'GooglePlaces'
  # Pods for weatr

  target 'weatrTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weatrUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
